url: "https://guysa.github.io"
permalink: /writing/:title/
markdown: kramdown

plugins:
  - jekyll-sitemap

name: Guy Sapire
description: "Guy Sapire — math PhD student working in algebraic geometry and number theory."

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - scripts
