permalink: /writing/:title/
markdown: kramdown

plugins:
  - jekyll-sitemap

name: Guy Sapire
description: "Guy Sapire — PhD student and developer."

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
